# Generated by Django 5.0.6 on 2024-05-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_recommendation_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='publication_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
