# Generated by Django 5.0.6 on 2024-05-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_alter_recommendation_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
